### ISSUE TITLE
File not found error when using `False` in cd.log()

### ISSUE THREAD

**Issue by Superigi** [dudeisbrendan03/consoleTools#1]
consoleDisplay.log() returns a file not found error even if I use False.
cd.log('e','a',False)
...[FileNotFoundError]...

**Comment by dudeisbrendan03** [comment]
Currently expected. Searching for cause

**Comment by dudeisbrendan03** [comment]
update
__________
Caused when the script is not ran from the folder it is located in

**Comment by dudeisbrendan03** [comment]
Until I can figure out how to solve this correctly, I've added a `./` before referencing the folder `logs` and you can just specify a custom log with `cd.log(blahblahblah,file="logfile")`
